export const STATUS_CODE_SUCCESS = [200, 201, 204];
export const STATUS_CODE_CLIENT_ERROR = [400, 401, 403, 404, 409];
export const STATUS_CODE_SERVER_ERROR = [500, 502, 503, 504];
export const STATUS_CODE_LOST_CONNECTION = 0;
export const STATUS_CODE_ERROR_REQUEST = -1;
export const STATUS_CODE_ALL_ERROR = [
  ...STATUS_CODE_CLIENT_ERROR,
  ...STATUS_CODE_SERVER_ERROR,
  STATUS_CODE_LOST_CONNECTION,
  STATUS_CODE_ERROR_REQUEST,
];

export const AVATAR_MAX_SIZE_MB = 2;
export const AVATAR_MAX_SIZE = AVATAR_MAX_SIZE_MB * 1024 * 1024;
export const POST_PICTURE_MAX_SIZE_MB = 10;
export const POST_PICTURE_MAX_SIZE = POST_PICTURE_MAX_SIZE_MB * 1024 * 1024;
